# Generated by Django 2.2 on 2019-11-03 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('began_at', models.DateTimeField(auto_now_add=True, verbose_name='Began job')),
                ('ended_at', models.DateTimeField(auto_now=True, verbose_name='Ended job')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_team', to='webapp.Project', verbose_name='Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_team', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
